version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.13
    container_name: 'salmonia-nginx'
    ports:
      - '8888:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/salmoniaNW
      - ./nginx/log:/var/log/nginx
    depends_on:
      - python3
  python3:
    restart: always
    build:
      context: ./salmonia
      dockerfile: Dockerfile
    container_name: 'python3'
    command: python /salmoniaNW/main.py
    working_dir: '/salmoniaNW/'
    tty: true
    volumes:
      - ./salmonia:/salmoniaNW
      - ./data:/data
  express:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: 'salmonia-api'
    ports:
      - '3000:3000'
    depends_on:
      - python3
    volumes:
      - ./data:/data
